model:
  latent_multiplier: -1
  latent_size: 1024
  forecast_steps: 1
  base_dt: 21600
  num_layers: 8
  bias_channels: 4
  velocity_vectors: 256
  diffusion_size: 1024
  reaction_size: 1024
  adv_interpolation: bicubic
  projected_advection: true
  num_encoder_layers: 1
  noise_type: raw_noise  # raw_noise or grf_noise
  grf_effective_resolution: 5
  grf_n_waves: null
  noise_channels: 4
  noise_mlp_hidden_dim: 32
init:
  seed: 42
  checkpoint_path: null #/home/saz001/ss8/paradis/released_versions/1_deg/v1.01/01/phase_1/logs/r4/checkpoints/last.ckpt
  restart: false
  checkpoint_type: deterministic   # deterministic or ensemble
dataset:
  root_dir: /home/cap003/site7/datasets/era5_1deg_13level/
  time_resolution: 6h
  n_time_inputs: 2
  sampling_interval: 6h
  prediction_delta: 6h
normalization:
  standard: true
compute:
  num_nodes: 1
  num_devices: 1
  accelerator: gpu
  use_amp: true
  batch_size: 1
  num_workers: 1
  compile: true
forecast:
  enable: false
  start_date: '2022-01-01'
  end_date: '2022-06-30'
  output_frequency: 1
  output_file: ./results/FT_LT72h_with_24hrWeights_2022.zarr/
training:
  max_epochs: -1
  max_steps: 30000
  progress_bar: true
  gradient_clip_val: null
  print_losses: false
  log_every_n_steps: 100
  log_dir: logs
  experiment_name: null
  num_ensemble_members: 2
  crps_alpha: 0.95
  conditioning_catchup_steps: 0
  spectral_crps:
    weight: 0.1 #put zero to turn off spectral afCRPS
    grid: equiangular
  dataset:
    start_date: '1990-01-01'
    end_date: '2019-12-31'
    preload: false
  validation_dataset:
    start_date: '2020-01-01'
    end_date: '2020-12-31'
    preload: false
    validation_every_n_steps: null
    validation_batches: null
  optimizer:
    lr: 1e-5
    weight_decay: 0.01
    beta1: 0.9
    beta2: 0.95
  early_stopping:
    enabled: false
    patience: 8
  loss_function:
    type: reversed_huber
    delta_loss: 1.0
    lat_weights: true
    validation_loss: null
  checkpointing:
    enabled: true
  scheduler:
    one_cycle:
      enabled: false
      warmup_pct_start: 0.0
      lr_div_factor: 1
      lr_final_div: 100
    reduce_lr:
      enabled: false
      factor: 0.75
      patience: 3
      threshold: 0.0001
      threshold_mode: rel
      min_lr: 1.0e-07
    wsd:
      enabled: true
      warmup: 1000
      decay: 0.2
  variable_loss_weights:
    atmospheric:
      wind_x: 1.0
      wind_y: 1.0
      wind_z: 1.0
      geopotential: 1.0
      specific_humidity: 1.0
      temperature: 1.0
      vertical_velocity: 1.0
    surface:
      wind_x_10m: 1.0
      wind_y_10m: 1.0
      wind_z_10m: 1.0
      2m_temperature: 1.0
      mean_sea_level_pressure: 1.0
  reports:
    enable: true
    features:
    - geopotential_h500
features:
  pressure_levels:
  - 50
  - 100
  - 150
  - 200
  - 250
  - 300
  - 400
  - 500
  - 600
  - 700
  - 850
  - 925
  - 1000
  base:
    atmospheric:
    - geopotential
    - wind_x
    - wind_y
    - wind_z
    - specific_humidity
    - temperature
    - vertical_velocity
    surface:
    - wind_x_10m
    - wind_y_10m
    - wind_z_10m
    - 2m_temperature
    - mean_sea_level_pressure
   
  input:
    atmospheric: ${features.base.atmospheric}
    surface: ${features.base.surface}
    forcings:
    - toa_incident_solar_radiation
    - sin_time_of_day
    - cos_time_of_day
    - sin_year_progress
    - cos_year_progress
    constants:
    - geopotential_at_surface
    - land_sea_mask
    - lon_spacing
    - cos_latitude
    - cos_longitude
    - sin_longitude
    - latitude
    - longitude
  output:
    atmospheric: ${features.base.atmospheric}
    surface: ${features.base.surface}

